#!/usr/bin/python3
def raise_exception():
    return "5" / 4
